dict = {'pressure': ('Pressure: ', 'Давление: '),
        'humidity': ('Humidity: ', 'Влажность: '),
        'pres_q': ('mm Hg St  ', 'мм. рт. ст.  '),
        'swipe': ('swipe Up to Renew', 'смахните Вверх для Обновления'),
        'renew': ('Renewed: ', 'Обновлено: '),
        'settings': ('Settings', 'Настройки'),
        'just': ('just', 'только что'),
        'less than an hour': ('less than an hour', 'меньше часа'),
        'hours ago': (' hours ago', ' час. назад'),
        'yesterday': ('yesterday', 'вчера'),
        'long ago': ('long ago', 'давно'),
        'morning': ('morning', 'утро'),
        'day': ('day', 'день'),
        'evening': ('evening', 'вечер'),
        'wind_speed': (' m/s ', ' м/с '),
        }